# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: deploy

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches: [master]
  # Trigger manually by an user.
  workflow_dispatch:

jobs:
  deploy:
    # NOTE: This name appears in GitHub's Checks API.
    name: deploy
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    # Setup github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn build
      # https://github.com/actions/upload-pages-artifact#example-permissions-fix-for-linux
      - name: Ensure build files have proper permissions
        run: |
          chmod -c -R +rX "dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
